package com.sriayur.entity;
// Generated Sep 12, 2021, 9:12:12 PM by Hibernate Tools 5.4.30.Final

/**
 * Delivery generated by hbm2java
 */
public class Delivery implements java.io.Serializable {

	private int deliveryId;
	private ProductOrder productOrder;
	private String deliveryname;
	private String description;

	public Delivery() {
	}

	public Delivery(int deliveryId, ProductOrder productOrder, String deliveryname, String description) {
		this.deliveryId = deliveryId;
		this.productOrder = productOrder;
		this.deliveryname = deliveryname;
		this.description = description;
	}

	public int getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(int deliveryId) {
		this.deliveryId = deliveryId;
	}

	public ProductOrder getProductOrder() {
		return this.productOrder;
	}

	public void setProductOrder(ProductOrder productOrder) {
		this.productOrder = productOrder;
	}

	public String getDeliveryname() {
		return this.deliveryname;
	}

	public void setDeliveryname(String deliveryname) {
		this.deliveryname = deliveryname;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
