package com.sriayur.entity;
// Generated Sep 12, 2021, 9:12:12 PM by Hibernate Tools 5.4.30.Final

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private int paymentId;
	private ProductOrder productOrder;
	private String paymername;
	private String description;

	public Payment() {
	}

	public Payment(int paymentId, ProductOrder productOrder, String paymername, String description) {
		this.paymentId = paymentId;
		this.productOrder = productOrder;
		this.paymername = paymername;
		this.description = description;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public ProductOrder getProductOrder() {
		return this.productOrder;
	}

	public void setProductOrder(ProductOrder productOrder) {
		this.productOrder = productOrder;
	}

	public String getPaymername() {
		return this.paymername;
	}

	public void setPaymername(String paymername) {
		this.paymername = paymername;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
