package com.sriayur.entity;
// Generated Sep 12, 2021, 9:12:12 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int productId;
	private Category category;
	private String productname;
	private String farmer;
	private String description;
	private String sku;
	private byte[] image;
	private float price;
	private Date mfgDate;
	private Date expiryDate;
	private Set reviews = new HashSet(0);
	private Set orderDetails = new HashSet(0);

	public Product() {
	}

	public Product(int productId, Category category, String productname, String farmer, String description, String sku,
			byte[] image, float price, Date mfgDate, Date expiryDate) {
		this.productId = productId;
		this.category = category;
		this.productname = productname;
		this.farmer = farmer;
		this.description = description;
		this.sku = sku;
		this.image = image;
		this.price = price;
		this.mfgDate = mfgDate;
		this.expiryDate = expiryDate;
	}

	public Product(int productId, Category category, String productname, String farmer, String description, String sku,
			byte[] image, float price, Date mfgDate, Date expiryDate, Set reviews, Set orderDetails) {
		this.productId = productId;
		this.category = category;
		this.productname = productname;
		this.farmer = farmer;
		this.description = description;
		this.sku = sku;
		this.image = image;
		this.price = price;
		this.mfgDate = mfgDate;
		this.expiryDate = expiryDate;
		this.reviews = reviews;
		this.orderDetails = orderDetails;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getFarmer() {
		return this.farmer;
	}

	public void setFarmer(String farmer) {
		this.farmer = farmer;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public Date getMfgDate() {
		return this.mfgDate;
	}

	public void setMfgDate(Date mfgDate) {
		this.mfgDate = mfgDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
